tasks:
  - name: Dependencies & compile
    init: ./mvnw verify

vscode:
  extensions:
    - redhat.java
    - redhat.vscode-xml
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test   
    - gabrielbb.vscode-lombok 